## Python 數值運算程式庫- NumPY
### NumPy是Pandas關鍵梁柱, 要充份發揮Pandas能力, 需了解NumPy核心元件及概念
### NumPy 適合用於數學運算與資料較龐大時的運算，使用 NumPy 會讓你程式碼更有效率之外，也能用較少程式碼來完成。
### NumPy可以操作多重維度陣列, 底層是以C程Fortran語言實作, 具備平行處理能力, 處理速度快
### NumPy生態系統包括: SciPy (科學計算), Scikit-learn (機器學習演算法)

### 1. 建立陣列

In [1]:
import numpy as np # import套件名稱 as 別名

# 一維陣列/矩陣創建
a = [1,2,3,4]  #list
a = np.array(a) #Numpy array
a

array([1, 2, 3, 4])

In [2]:
type(a)  # 多維陣列

numpy.ndarray

In [3]:
a.shape # 知道多維陣列的形狀，型態是 tuple。

(4,)

In [7]:
# 改變陣列的形狀與維度
# https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html
a= np.array([1,2,3,4,5,6,7,8])
a = a.reshape([2,4])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
a.shape 

(2, 4)

In [8]:
a = a.reshape([2,2,2])
a

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [9]:
a.shape

(2, 2, 2)

In [10]:
a.ndim # 多維陣列的維度

3

In [5]:
a = np.zeros([2,3])
a

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [6]:
a = np.ones([2,3])
a

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [7]:
# https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.dtypes.html
a.dtype

dtype('float64')

In [8]:
a = np.random.random((2,3))
a

array([[ 0.14009624,  0.7427953 ,  0.17659659],
       [ 0.3850684 ,  0.15762126,  0.73059646]])

## 2. 陣列索引與切片

In [25]:
a = np.array([1,2,3,4,5,6])  #索引值有0算起
a[3]

4

In [26]:
a = a[3:5]   # 索引 3 到 4
a

array([4, 5])

In [29]:
a = np.array([1,2,3,4,5,6])
a[:4:2] = 0   # 索引 0 到 3, 間隔為 2
a

array([0, 2, 0, 4, 5, 6])

In [30]:
a[::-1]  # 反轉

array([6, 5, 4, 0, 2, 0])

In [8]:
a = np.arange(16, dtype = 'int32')
a = a.reshape([2,2,4])
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [34]:
a[0]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [35]:
a[1]

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [36]:
a[0, 1]

array([4, 5, 6, 7])

In [37]:
a[0,1,1]

5

In [39]:
a[0,:,1:3]    # 1:3表示 1, 2

array([[1, 2],
       [5, 6]])

## 3. 基本運算

In [40]:
a = np.array([1,2,3,4,5,6])
print ("Numpy Array:" , a)
print ("加:", a + a)
print ("減:" , a - a)
print ("乘:" , a * a)
print ("除:" , a / a)
print ("*0.5" , a * 0.6)

Numpy Array: [1 2 3 4 5 6]
加: [ 2  4  6  8 10 12]
減: [0 0 0 0 0 0]
乘: [ 1  4  9 16 25 36]
除: [ 1.  1.  1.  1.  1.  1.]
*0.5 [ 0.6  1.2  1.8  2.4  3.   3.6]


In [4]:
a = np.array([1,2,3,4,5,6])
print ("absolute value:\n" , np.absolute(a * -0.5))#絕對值
print ("square root:\n" , np.sqrt(a)) #平方根
print ("sin:\n" , np.sin(a)) # sin(a)
print ("log(base e):\n" , np.log(a)) #log(base e)
print ("Mean:" , a.mean()) #平均數
print ("Std:" , a.std()) #標準差
print ("Sum:" , a.sum()) #加總
print ("Max:" , a.max()) #取最大數
print ("Min:", a.min()) # 取最小數

absolute value:
 [ 0.5  1.   1.5  2.   2.5  3. ]
square root:
 [ 1.          1.41421356  1.73205081  2.          2.23606798  2.44948974]
sin:
 [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
log(base e):
 [ 0.          0.69314718  1.09861229  1.38629436  1.60943791  1.79175947]
Mean: 3.5
Std: 1.70782512766
Sum: 21
Max: 6
Min: 1


In [50]:
a = np.arange(8).reshape((2,4))
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [51]:
print ("第二軸的累和:\n" , np.cumsum(a, axis=1)) 

第二軸的累和:
 [[ 0  1  3  6]
 [ 4  9 15 22]]


In [13]:
#矩陣運算
a = np.array([[1,2,3],[2,4,6]]) #2*3
b = np.array([[0,0,0],[1,1,1]]) #2*3
print("a\n",a)
print("b\n",b)
print ("元素相乘:\n" , a * b)
print ("轉置矩陣(Transpose)\n" , b.transpose())
print ("矩陣相乘:\n" , np.dot(a, b.transpose()))   #https://zh.wikipedia.org/wiki/%E7%9F%A9%E9%99%A3%E4%B9%98%E6%B3%95

a
 [[1 2 3]
 [2 4 6]]
b
 [[0 0 0]
 [1 1 1]]
元素相乘:
 [[0 0 0]
 [2 4 6]]
轉置矩陣(Transpose)
 [[0 1]
 [0 1]
 [0 1]]
矩陣相乘:
 [[ 0  6]
 [ 0 12]]
